export default {
    API_REQUEST: 'API_REQUEST',
    API_SUCCESS: 'API_SUCCESS',
    API_AGGREGATED_REQUEST: 'API_AGGREGATED_REQUEST',
    API_AGGREGATED_SUCCESS: 'API_AGGREGATED_SUCCESS',
    API_ERROR: 'API_ERROR',
    API_CLEAR: 'API_CLEAR'
};