export default {
    API_REQUEST: 'API_REQUEST',
    API_RESPONSE: 'API_RESPONSE',
    API_ERROR: 'API_ERROR',
    API_CLEAR: 'API_CLEAR',
    API_AGGREGATED_GET: 'API_AGGREGATED_REQUEST',
    API_AGGREGATED_RESPONSE: 'API_AGGREGATED_RESPONSE'
};